### ISSUE TITLE
Blender 2.8: Split Node Seems Broken

### ISSUE THREAD

**Issue by RSWilli** [MaximeHerpin/modular_tree#169]
I downloaded the blender_28 Branch to use in my Blender 2.8.

But the latest Update seems to have broken the "Split Node". When I connect the "Trunk Node" to anything other than the "Split Node" (eg. branch/grow), then it correctly works and the trunk gets some branches.

On the other side, when I put a Split after the Trunk or in between the Trunk and Branch/Grow, the Trunk stays as if I never connected the trunk node to anything else.

**Comment by MaximeHerpin** [comment]
The split node creates opportunities for branches to fork. In order to see the effect of a split node, you have to put a grow node after it, the you will see the forks turn into branches.

Example
trunk with split -> no visible changes
![split](https://user-images.githubusercontent.com/15239308/50638979-f3e9b400-0f5f-11e9-9c53-50786b676df8.PNG)

trunk then split then grow -> the splits created by the split node are grown into branches
![split grow](https://user-images.githubusercontent.com/15239308/50639017-1380dc80-0f60-11e9-8a39-7cc53595abff.PNG)
