### ISSUE TITLE
Particles problem (one tree - multiple times)

### ISSUE THREAD

**Issue by JakubPelka** [MaximeHerpin/modular_tree#219]
Hi, I am lucky with your plugin, but have a small related problem. Maybe you could help.
I created a tree (it would be nice if there were some coniferous twigs as well) and I'd like to reuse it to create a small forest.
I have a terrain model, I use hair particles system and I am only able to get a trunk and branches to the new particles system. How can I reuse all tree with twigs/leaves ?
Will be glad for your help!

**Comment by CryOns** [comment]
> Hi, I am lucky with your plugin, but have a small related problem. Maybe you could help.
> I created a tree (it would be nice if there were some coniferous twigs as well) and I'd like to reuse it to create a small forest.
> I have a terrain model, I use hair particles system and I am only able to get a trunk and branches to the new particles system. How can I reuse all tree with twigs/leaves ?
> Will be glad for your help!

I can help you, so follow these instructions:

Abstract: If your tree consists of more than one object, add it to a specific collection just for it and then, in Render, in the particle system, instead of Object, select Collection and then select the collection in which your composite tree is.

What I meant to say: Add your vegetation to a new collection (if it is a tree, add the trunk and leaves to the same collection), in the particle system, in Render, instead of Object, select Collection. Remember, your objects must be isolated in a specific collection for them, separate from all other objects in the scene. For each set of objects, you will have to add a new collection and isolate them. For example, if you have 10 different trees in the scene, you will have to create a collection for each one of them (if they are composed of separate objects, for example, when leaves and trunk are not part of the same object, otherwise it will not be necessary to create a collection, since it is a single object).

**Comment by JakubPelka** [comment]
Hi, and thank you!

I did try it but I get trees without leaves. 
Can you please check it and tell me what I do wrong?
I attach Blend file so you can check it. Will be glad for your help.
[forest.zip](https://github.com/MaximeHerpin/modular_tree/files/4853758/forest.zip)

**Comment by CryOns** [comment]
> Hi, and thank you!
> 
> I did try it but I get trees without leaves.
> Can you please check it and tell me what I do wrong?
> I attach Blend file so you can check it. Will be glad for your help.
> [forest.zip](https://github.com/MaximeHerpin/modular_tree/files/4853758/forest.zip)

Easy. In your case, the leaves of the tree are instances, that is, they are multiplied by another particle system and, being instances, the blender cannot reproduce the instance of an instance in the particle system:
https://youtu.be/-uo507t1x0M

**Comment by JakubPelka** [comment]
Now it all makes sense! 
Super tutorial and explanation! 
It was something I was looking for!

**Comment by CryOns** [comment]
> Now it all makes sense!
> Super tutorial and explanation!
> It was something I was looking for!
> Thanks a lot!

I will try to make a more explanatory video using the same scene you provided. In the video from the link above, I did everything very quickly because I was out of time. For example, in the video link above, I delete the original object that is used as a leaf for the tree, but you can simply hide it and place it outside the collection of the composite tree. You also do not need to delete the original instance of the leaves, just hide or disable it in the particle system, so you can reuse it later, I believe.

**Comment by CryOns** [comment]
Done! The vídeo is self-explanatory: https://www.youtube.com/watch?v=4Xw0PLY9v4o
