### ISSUE TITLE
Mtree 2.8 not working on Mac OSX

### ISSUE THREAD

**Issue by charliehewitt113** [MaximeHerpin/modular_tree#250]
Hello. I have Blender 2.91 running on Mac OSX. I have downloaded Moduar_tree (ver. 2.8) from Github, installed it via Preferences > Addons, and enabled it with the checkbox. However, the option to add the Mesh Tree doesn't appear when I go to Add > Mesh. Can anyone help please? I have seen from another post that it should be possible to run Mtree 2.8 in Blender 2.91. Is this possible? Thanks. 

![image](https://user-images.githubusercontent.com/78046749/105897777-85796200-6010-11eb-8829-e6f6d1adb88a.png)

![image](https://user-images.githubusercontent.com/78046749/105897882-a8a41180-6010-11eb-9ffe-dd33c940276d.png)

**Comment by bassbum37** [comment]
Trees are created from the MTree node editor instead of the add menu. Open the editor from the editor type drop-down and create a new Node Tree. The 'Tree parameters' node has a 'Create Tree' button which will generate your tree. Once you've created a tree it becomes associated with the node tree and the "Create Tree' button will disappear, whenever you make a change in the node tree an "Update Tree' button will appear.

MTree node editor:
![image](https://user-images.githubusercontent.com/27635384/105910900-91a4f580-5ff7-11eb-88c1-75c755b17a73.png)

Create a Node Tree:
![image](https://user-images.githubusercontent.com/27635384/105910862-818d1600-5ff7-11eb-9a68-275504491abc.png)

The create button:
![image](https://user-images.githubusercontent.com/27635384/105911242-f95b4080-5ff7-11eb-869b-8870f956290f.png)

Our tree!
![image](https://user-images.githubusercontent.com/27635384/105911408-27408500-5ff8-11eb-9ccf-746842a5265c.png)

**Comment by charliehewitt113** [comment]
Ah yes, sorry my bad. Thank you very much for your help, much appreciated.
