### ISSUE TITLE
Its not even working!!!

### ISSUE THREAD

**Issue by edwin77577** [MaximeHerpin/modular_tree#274]

**Comment by Sinasta** [comment]
Well thats not a nice way to ask for usage instructions.

**Comment by kahpas** [comment]
If you expect anybody to take care of your issue you should provide more details like: symptoms, error logs, version numbers, the OS you are using etc. I know such issues are frustrating, but they will never get fixed by shouting at the developers.

You should also (if you have not done so already) read other issues to see if somebody has the same error as you.

Pleas add further details or close the issue.
